language: csharp
solution: MessagePack.sln
script:
  - curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install > brewcask.rb
  - sudo ruby -e brewcask.rb
  - sudo brew update
  - sudo brew tap caskroom/cask
  - sudo brew cask install dotnet
  - cd sandbox/SharedData
  - nuget restore
  - cd src/MessagePack.UniversalCodeGenerator
  - dotnet build
  - dotnet run -- -i ../../sandbox/SharedData/SharedData.csproj -o ../../output.txt
  