language: csharp
solution: MessagePack.sln
matrix:
  include:
    - dotnet: 2.1.502
      os: osx
    - dotnet: 2.1.502
      os: linux
    - dotnet: 2.2.103
      os: linux
      dist: xenial
script:
  - cd src/MessagePack
  - dotnet build -f netstandard2.0
  - dotnet build -f netstandard1.6
  - "msbuild /t:Build"
  - cd ../MessagePack.UniversalCodeGenerator
  - dotnet run -- -i ../../sandbox/SharedData/SharedData.csproj -o ../../output.txt
  - cat ../../output.txt
