language: csharp
solution: MessagePack.sln
matrix:
  include:
    - dotnet: 2.1.502
    - mono: 5.16
script:
  - cd src/MessagePack.UniversalCodeGenerator
  - dotnet build
  - dotnet run -- -i ../../sandbox/SharedData/SharedData.csproj -o ../../output.txt
