trigger:
  paths:
    exclude: ["doc", "*.md"]

variables:
  TreatWarningsAsErrors: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  BuildPlatform: Any CPU

jobs:
- job: macOS
  pool: Hosted macOS
  steps:
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        verbosityRestore: normal
        projects: "**/*.sln"
        feedToUse: config
        nugetConfigPath: nuget.config
    - task: DotNetCoreCLI@2
      inputs:
        command: build
        projects: "src/MessagePack.UniversalCodeGenerator/MessagePack.UniversalCodeGenerator.csproj"
        verbosityRestore: normal
        feedToUse: config
        nugetConfigPath: nuget.config
      displayName: Build MessagePack.sln
    - task: DotNetCoreCLI@2
      displayName: prepare test project
      inputs:
        command: restore
        verbosityRestore: normal
        feedToUse: config
        nugetConfigPath: nuget.config
        projects: "sandbox/TestData.SubDir/TestData.SubDir.csproj"
    - task: DotNetCoreCLI@2
      displayName: run test subdir
      inputs:
        command: run
        verbosityRestore: normal
        feedToUse: config
        nugetConfigPath: nuget.config
        arguments: "--project src/MessagePack.UniversalCodeGenerator/MessagePack.UniversalCodeGenerator.csproj -- -i sandbox/TestData.SubDir/TestData.SubDir.csproj -o Generated.cs"
